# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments


# Permalinks
permalink:        pretty

# Setup
title:            Dawine Pierre
tagline:          'Ing., Data Scientist, GIS Specialist'
description:      'Ing., Data Scientist, GIS Specialist'
url:              https://pdawine.github.io/
baseurl:          /

author:
  name:           'Dawine Pierre'
#  url:            https://twitter.com/pdawine

paginate:         5

# Custom vars
version:          2.1.0


github:
me: https://github.com/pdawine
