# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments


# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dawine Pierre
tagline:          'Ing., Data Scientist, GIS Specialist'
description:      'Ing., Data Scientist, GIS Specialist'
url:              http://re-s.org/
baseurl:          /

author:
  name:           'Dawine Pierre'
#  url:            https://twitter.com/pdawine

paginate:         5

plugins: [jekyll-paginate]
paginate_path: "page:num"


# Custom vars
version:          2.1.0


github:
me: https://github.com/pdawine
